apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: simple-cicd
    app.kubernetes.io/part-of: simple-cicd
    control-plane: controller-manager
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controllerManager.type }}
  selector:
    control-plane: controller-manager
  {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.controllerManager.ports | toYaml | nindent 2 -}}