apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-cicd.serviceAccountName" . }}
  namespace: {{ include "simple-cicd.namespace" . }}
  labels:
    {{- include "simple-cicd.labels" . | nindent 4 }}
