apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-cicd.fullname" . }}
  namespace: {{ include "simple-cicd.namespace" . }}
  labels:
    {{- include "simple-cicd.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "simple-cicd.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: webhook
