---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflowwebhookrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflowwebhookrequests/finalizers
  verbs:
  - update
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflowwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflowwebhooks/finalizers
  verbs:
  - update
