# permissions for end users to edit workflowwebhookrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workflowwebhookrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple-cicd
    app.kubernetes.io/part-of: simple-cicd
    app.kubernetes.io/managed-by: kustomize
  name: workflowwebhookrequest-editor-role
rules:
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflowwebhookrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simple-cicd.jlsalvador.online
  resources:
  - workflowwebhookrequests/status
  verbs:
  - get
