# Echo "hello" and launch the "random" Workflow afterward.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: hello
spec:
  jobsToBeCloned:
    - name: echo-hello
  next:
    - name: random
      # when: # when is optional, by default is "Always"

---
# Echo "hi" and perform no additional actions.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: hi
spec:
  jobsToBeCloned:
    - name: echo-hi

---
# This "random" Workflow will launch two pods, which will exit randomly as
# successful or not.
# Depending on the three possible states: (all success, all failures, some
# success and some failures), it will launch the Workflow "all-ok", "all-bad",
# or "some-successes" and "some-failures".
#
# The idea with this Workflow is to present to you the possibility to launch
# different Workflows depending on the success (or failure) of the last ones.
# A.K.A. conditional Workflows.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: random
spec:
  jobsToBeCloned:
    - name: exit-random
    - name: exit-random
  next:
    - name: all-ok
      when: OnSuccess
    - name: all-bad
      when: OnFailure
    - name: some-successes
      when: OnAnySuccess
    - name: some-failures
      when: OnAnyFailure

---
# Echo "all was ok" and proceed to the "bye" Workflow unconditionally.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: all-ok
spec:
  jobsToBeCloned:
    - name: echo-all-ok
  next:
    - name: bye
      when: Always

---
# Echo "all was bad" and proceed to the "bye" Workflow unconditionally.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: all-bad
spec:
  jobsToBeCloned:
    - name: echo-all-bad
  next:
    - name: bye
      when: Always

---
# Echo "some successes" and proceed to the "bye" Workflow unconditionally.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: some-successes
spec:
  jobsToBeCloned:
    - name: echo-some-successes
  next:
    - name: bye
      when: Always

---
# Echo "some failures" and proceed to the "bye" Workflow unconditionally.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: some-failures
spec:
  jobsToBeCloned:
    - name: echo-some-failures
  next:
    - name: bye
      when: Always

---
# Echo "bye" and perform no additional actions.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: bye
spec:
  jobsToBeCloned:
    - name: echo-bye

---
# Since this Workflow has suspend=true, it will not execute when triggered
# by a WorkflowWebhook or another Workflow.
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: suspended
spec:
  suspend: true
  jobsToBeCloned:
    - name: echo-hi
