apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: hello
spec:
  jobsToBeCloned:
    - name: echo-hello
  next:
    - name: random
      # when: # when is optional, by default is "Always"
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: hi
spec:
  jobsToBeCloned:
    - name: echo-hi
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: random
spec:
  jobsToBeCloned:
    - name: exit-random
    - name: exit-random
  next:
    - name: all-ok
      when: OnSuccess
    - name: all-bad
      when: OnFailure
    - name: some-successes
      when: OnAnySuccess
    - name: some-failures
      when: OnAnyFailure
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: all-ok
spec:
  jobsToBeCloned:
    - name: echo-all-ok
  next:
    - name: bye
      when: Always
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: all-bad
spec:
  jobsToBeCloned:
    - name: echo-all-bad
  next:
    - name: bye
      when: Always
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: some-successes
spec:
  jobsToBeCloned:
    - name: echo-some-successes
  next:
    - name: bye
      when: Always
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: some-failures
spec:
  jobsToBeCloned:
    - name: echo-some-failures
  next:
    - name: bye
      when: Always
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: bye
spec:
  jobsToBeCloned:
    - name: echo-bye
---
apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: Workflow
metadata:
  name: suspended # This Workflow will not be triggered
spec:
  jobsToBeCloned:
    - name: echo-hi
