apiVersion: simple-cicd.jlsalvador.online/v1alpha1
kind: WorkflowWebhookRequest
metadata:
  name: sample
spec:
  workflowWebhook:
    name: sample
  host: simplecicd-controller-manager.simplecicd-system:9000
  method: GET
  url: /default/sample
  headers:
    Authorization:
      - Bearer
      - mytoken123
    X-SECRET:
      - secret-passphrase
  # {
  #   "username": "user",
  #   "password": "pass"
  # }
  body: ewogICJ1c2VybmFtZSI6ICJ1c2VyIiwKICAicGFzc3dvcmQiOiAicGFzcyIKfQo=
