apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-cicd.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: simple-cicd
    app.kubernetes.io/part-of: simple-cicd
    control-plane: controller-manager
  {{- include "simple-cicd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "simple-cicd.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}