apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: v1
kind: Namespace
metadata:
  name: crossns-example
---
# Job that randomly exits with code 0 or 1 (OK or Error)
apiVersion: batch/v1
kind: Job
metadata:
  name: job-example-random-exit
  namespace: example
spec:
  suspend: true # Required to be true to disallow Kubernetes to start this job when it will be created
  backoffLimit: 0 # If this Job fail do not try to run it again
  template:
    spec:
      containers:
        - name: random-exit
          image: bash
          command: ["sh", "-c", "exit $$(($RANDOM % 2))"] # Sometimes will fails
        - name: echo-request
          image: bash
          command:
            # Simple CI/CD will mounts the next request payloads inside all Pods
            - sh
            - -c
            - |
              echo "Host:      $(cat /var/run/secrets/kubernetes.io/request/host)"
              echo "Headers:   $(cat /var/run/secrets/kubernetes.io/request/headers)"
              echo "Method:    $(cat /var/run/secrets/kubernetes.io/request/method)"
              echo "URL:       $(cat /var/run/secrets/kubernetes.io/request/url)"
              echo "From:      $(cat /var/run/secrets/kubernetes.io/request/remoteAddr)"
              echo "At:        $(cat /var/run/secrets/kubernetes.io/request/timestamp)"
              echo "Body:      $(cat /var/run/secrets/kubernetes.io/request/body)"
      restartPolicy: Never # Do not re-run the pod if something fails
---
# Job that echoes "ERROR"
apiVersion: batch/v1
kind: Job
metadata:
  name: job-example-error
  namespace: crossns-example # Job namespace. Optional
spec:
  suspend: true # Required to be true to disallow Kubernetes to start this job when it will be created
  template:
    spec:
      containers:
        - name: error
          image: bash
          command: ["echo", "ERROR"]
      restartPolicy: Never # Do not re-run the pod if something fails
---
# Workflow that will clones the "job-example-error" Job
apiVersion: simple-cicd.jlsalvador.online/v1alpha2
kind: Workflow
metadata:
  name: workflow-example-some-failures
  namespace: crossns-example # Workflow namespace. Optional.
spec:
  jobsToBeCloned:
    - name: job-example-error # Job name that will cloned
      namespace: crossns-example # Job namespace. Optional.
---
# Workflow that will clones the "job-example-random-exit" Job and
# triggers the "workflow-example-some-failures" Workflow on any Job failure
apiVersion: simple-cicd.jlsalvador.online/v1alpha2
kind: Workflow
metadata:
  name: workflow-example
  namespace: example
spec:
  jobsToBeCloned:
    - name: job-example-random-exit # Job name that will cloned
  next:
    - name: workflow-example-some-failures
      namespace: crossns-example # Workflow namespace. Optional.
      when: OnAnyFailure # Only run this Workflow if some of the jobsToBeCloned fails
---
# WorkflowWebhook set the simple-cicd operator to listen for requests on the path "$namespace/$name"
apiVersion: simple-cicd.jlsalvador.online/v1alpha2
kind: WorkflowWebhook
metadata:
  name: workflowwebhook-example
  namespace: example
spec:
  workflows:
    - name: workflow-example # Workflow that will be initiated
